mendersoftware/workflows

.gitlab-ci.yaml
changelog: none
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
=> CI: Initialize gitlab-ci

Dockerfile
=> QA-139 fixing entrypoint to match other services

config/config.go
=> MEN-3060 default mongo url fix

Makefile, api/http/workflow.go, api/http/workflow_test.go, app/server/server.go, app/worker/worker.go, docker-compose.yaml, store/datastore.go, store/mock/datastore_mock.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>
=> Finalize workflows to fully support create_artifact_worker

.gitignore, .gitlab-ci.yml, Dockerfile.worker, worker/config.yaml, worker/decommission_device.json, worker/provision_device.json
Initial implementation of the workflows-worker
This commit introduces the workflows worker, mainly using boilerplate
code, without the real implementation of the decommission_device and
provision_device workflows.
=> Build a new docker image, workflows-worker

.gitlab-ci.yml
Cherry picking e0bc382 into 1.0.x
=> Update docker:dind image tag to docker:19.03.5-dind - 1.0.x

Dockerfile.acceptance-testing, Dockerfile.acceptance-testing.worker, main.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Implementation of the workflow name inclusion / exclusion in the worker
was missing. This commit introduces inclusion / exclusion using query
filters, together with related unit tests.
=> Fix workflow name inclusion and exclusion

tests/tests/test_decommission_device.py, worker/decommission_device.json, worker/provision_device.json
Decommission and provision device workflows added.
=> MEN-2963 decommission and provision device workflows

app/worker/smtp.go, app/worker/smtp_test.go
=> MEN-2965 smtp workers: support for loading body from file

api/http/workflow.go, app/worker/http.go, app/worker/process.go, app/worker/smtp.go
* Auth passes host not host:port
* do not send AUTH if username not provided (required for tests)
* extra logging
=> MEN-2965 smtp: auth fixes and extra logging

app/worker/utils.go
=> MEN-2965 replace all values in processJobString

app/worker/process.go
=> Fix: add the result to the job, subsequent tasks may need it

.gitignore, app/server/server.go, app/worker/smtp.go, app/worker/smtp_test.go, app/worker/worker.go, config/config.go, main.go, model/job.go, store/datastore.go, store/mock/datastore_mock.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Adds:
* _list-jobs_ command
* pagination
* sorting (desc with `insert_time`)
* `insert_time` field added to jobs collection
* enable debug flag
* extra logging in worker
ChangeLog:none
=> Extra logging and go fmt

tests/mmock/inventory_POST_devices_v2.json, tests/tests/test_update_device_status.py, worker/update_device_status.json
=> MEN-3240 updating internal inventory url

README.md
=> list-jobs simple docs

.gitlab-ci.yml
The server image is already published thought the mendertesting
template.
=> [pipeline] New job to publish new style tags for the worker image

app/worker/smtp.go, app/worker/smtp_test.go, app/worker/utils.go, model/task.go
=> MEN-3509: add support for sending html (mime/alternative) messages

docs/workflows_api.yml
=> API spec fixes: schema and hostname - 1.1.x

docs/workflows_api.yml
=> Fix the title in the API documentation

api/http/router.go, api/http/workflow.go, api/http/workflow_test.go, store/datastore.go, store/mock/datastore_mock.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
I didn't create a new liveliness endpoint for this service as GET /status already existed.
=> MEN-3030: Add health check endpoint GET /health

.gitlab-ci.yml
=> MEN-2917: upgrade mongodb to 4.4

Dockerfile.acceptance-testing.worker, Dockerfile.worker, tests/mmock/inventory_PATCH_attributes.json, tests/tests/test_update_device_inventory.py, worker/update_device_inventory.json
Issue: https://tracker.mender.io/browse/MEN-3979
=> workflow for updating device inventory

app/worker/http.go, app/worker/http_test.go, app/worker/utils.go, app/worker/utils_test.go, docker-compose.yml, model/task.go, model/workflow_test.go, tests/docker-compose.yml
=> MEN-4110: add support for JSON body in HTTP tasks

app/worker/process.go, app/worker/process_test.go, docs/workflows_api.yml, model/task.go
=> Add retryDelaySeconds property to speficy retry delays in tasks

tests/docker-compose.yml
=> Add dependencies on mongodb in acceptance tests' docker composition

.gitlab-ci.yml, tests/Dockerfile, tests/docker-compose.acceptance.yml
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
=> tests: switched image used in acceptance tests to prebuilt one

app/worker/utils.go, app/worker/utils_test.go
=> Fix JSON serialization when working with bson primitives

Dockerfile.acceptance-testing.worker, Dockerfile.worker, api/http/workflow.go, app/worker/utils.go, app/worker/utils_test.go, model/job.go, tests/mmock/deployments_POST_configuration_deployment.json, tests/tests/test_deploy_device_configuration.py, worker/deploy_device_configuration.json
=> MEN-4429: new workflow deploy_device_configuration

Dockerfile.acceptance-testing.worker, Dockerfile.worker
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
=> sligthly simplified workflow definition copying

tests/mmock/deviceconnect_POST_check_update.json, tests/tests/test_deploy_device_configuration.py, worker/deploy_device_configuration.json
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
=> worker: config deployment triggers device update check

.gitlab-ci.yml
Following upstream update. See
https://github.com/mendersoftware/mendertesting/pull/141
=> [pipeline] Switch from dependencies to needs

.gitlab-ci.yml
Reverts mendersoftware/workflows#120
=> Revert "[pipeline] Switch from dependencies to needs"

.gitlab-ci.yml
(cherry picked from commit 019805e20080298e2e047c30ffa15fb9fc55b27e)
=> 1.4.x: Revert "[pipeline] Switch from dependencies to needs"

.gitlab-ci.yml
(cherry picked from commit 019805e20080298e2e047c30ffa15fb9fc55b27e)
=> 1.3.x: Revert "[pipeline] Switch from dependencies to needs"

.gitlab-ci.yml
(cherry picked from commit 019805e20080298e2e047c30ffa15fb9fc55b27e)
=> 1.1.x: Revert "[pipeline] Switch from dependencies to needs"

app/worker/process.go, app/worker/worker.go
=> Improve logging

app/worker/http_test.go, app/worker/utils.go
QA pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/324874549
Failures in mtls are expected (fixed in integration:master)
=> Improve processJobJSON to handle JSON input parameters and null values

Dockerfile.acceptance-testing.worker, Dockerfile.worker, tests/docker-compose.acceptance.yml, tests/mmock/reporting_POST_reindex_reporting.json, tests/tests/test_reindex_reporting.py, worker/reindex_reporting.json
https://tracker.mender.io/browse/MEN-4741
changelog: none
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
=> worker: reindex workflow for mender-reporting

tests/mmock/deviceconnect_DELETE_devices.json, tests/mmock/deviceconnect_DELETE_devices_with_tenant_id.json, worker/decommission_device.json
=> Fix: allow 404s in decommission device workflow from device{connect,config}

worker/decommission_device.json
=> Bump the decommission_device workflow's version

tests/mmock/deployments_DELETE_devices.json, tests/mmock/inventory_DELETE_device.json, tests/mmock/inventory_POST_devices.json, tests/tests/test_decommission_device.py, tests/tests/test_provision_device.py, worker/decommission_device.json, worker/provision_device.json
=> MEN-4525: use internal end-points to provision and decommission devices

app/worker/smtp.go, app/worker/smtp_test.go
=> MEN-5116: accept comma-separated list of addresses in the SMTP task

app/worker/smtp.go, app/worker/smtp_test.go
=> MEN-5124: add support for `Name <email@example.com>` mail sender/recipients

app/worker/smtp.go, app/worker/smtp_test.go
=> Fix string interpolation in email headers

api/http/workflow.go, api/http/workflow_test.go, app/worker/cli_test.go, app/worker/http_test.go, app/worker/process.go, app/worker/process_test.go, app/worker/smtp_test.go, model/job.go, store/datastore.go, store/mock/datastore_mock.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> MEN-4554 Version as optional parameter to the request.

app/worker/worker.go, client/nats/client.go, client/nats/mocks/Client.go
=> Set nats subscription's maxAckPending to the value of concurrency

.gitlab-ci.yml, api/http/logger.go, api/http/workflow.go, app/server/server.go, app/worker/http.go, app/worker/process.go, app/worker/smtp.go, app/worker/smtp_client.go, app/worker/smtp_client_mock.go, app/worker/utils.go, app/worker/worker.go, client/nats/client.go, main.go, model/job.go, model/workflow.go, store/datastore.go, store/mock/datastore_mock.go, store/mongo/datastore_mongo.go, store/mongo/dbsetup_test.go, store/mongo/migration_1_0_0.go
=> QA-235: pipeline: Switch to static checks by golangci-lint

tests/docker-compose.acceptance.yml, tests/mmock/azure-iot-manager_POST_devices.json, tests/mmock/azure-iot-manager_POST_devices_with_tenant_id.json, worker/decommission_device.json, worker/provision_device.json, worker/update_device_status.json
=> Rename azure-iot-manager to iot-manager

tests/tests/test_update_device_status.py, worker/provision_external_device.json, worker/update_device_status.json
Also removes deviceauth from the device provisioning workflow.
=> [MEN-5342] Remove azure parameters from status workflow and call iot-manager unconditionally

Dockerfile, Dockerfile.acceptance-testing, Dockerfile.acceptance-testing.worker, Dockerfile.worker
=> style: dockerfiles

app/worker/timer.go, app/worker/worker.go, go.mod, go.sum, main_debug.go, vendor/github.com/nats-io/nats.go/go_test.mod, vendor/github.com/nats-io/nats.go/go_test.sum, vendor/github.com/nats-io/nats.go/js.go, vendor/github.com/nats-io/nats.go/jsm.go, vendor/github.com/nats-io/nats.go/kv.go, vendor/github.com/nats-io/nats.go/object.go, vendor/modules.txt
This PR enhances workflows (worker) performance while under load.
:information_source: 36d9d315ff062841b038eb6b4cbb6eeb7b31b8f1 is the main commit, the rest is just for convenience
=> MEN-5528: Use a static pool of worker goroutines

Dockerfile, Dockerfile.acceptance-testing, Dockerfile.acceptance-testing.worker, Dockerfile.worker
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>
=> chore: moved docker image away from root

tests/run.sh, utils/mockgen.sh
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
=> chore: add the missing shell license headers

worker/decommission_device.json, worker/deploy_device_configuration.json, worker/provision_device.json, worker/provision_external_device.json, worker/reindex_inventory.json, worker/update_device_inventory.json, worker/update_device_status.json
Ticket: None
(cherry picked from commit cb2cd1f72c20581b03c7f204951eaa7b5072085c)
=> chore: Increment workflows version

.gitlab-ci.yml, Makefile
=> chore: add --no-deps when running the acceptance-testing container 

worker/decommission_device.json
Ticket: ME-41
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
=> ME-41: adjust device decommissioning workflow to the related code change

Dockerfile.acceptance-testing.worker, Dockerfile.worker, tests/tests/test_reindex_reporting_deployment.py, worker/reindex_reporting_deployment.json
Ticket: MEN-5930
Changelog: Ticket
=> feat: reindex_reporting_deployment workflow to index device deployments

LICENSE, LIC_FILES_CHKSUM.sha256
=> chore: update copyright year in the LICENSE file

main.go
Changelog: Title
Ticket: MEN-6698
=> fix: `migrate` command tries to create Jetstream consumer before stream

.gitlab-ci.yml, Dockerfile, Dockerfile.worker
Ticket: QA-613
Changelog: Added multiplatform build
=> Multiplatform build

.gitlab-ci.yml
Ticket: QA-613
Needs: https://github.com/mendersoftware/mendertesting/pull/280
=> Override the internal container image with a variable

.gitlab-ci.yml
Ticket: QA-620
Requires: https://github.com/mendersoftware/mender-test-containers/pull/415
=> fix pipeline acceptance tests

api/http/jobs.go, api/http/jobs_test.go, api/http/router.go, docs/workflows_api.yml, store/datastore.go, store/mock/datastore_mock.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Changelog: Title
Ticket: MEN-6791
=> feat: get job status by id

.gitlab-ci.yml
=> ci: update gitlab shared runners

.gitlab-ci.yml, LICENSE, LIC_FILES_CHKSUM.sha256, app/worker/timer.go, app/worker/worker.go, app/worker/worker_group.go
Backport #318 (MEN-7214) to 2.5.x
=> Backport #318 (MEN-7214) to 2.5.x

.gitlab-ci.yml
=> Adding gitlab dependency proxy

Dockerfile, Dockerfile.acceptance-testing, Dockerfile.acceptance-testing.worker, Dockerfile.worker
=> chore: align Docker files between OS and ENT flavours
