mendersoftware/workflows

Dockerfile
Makefile
README.md
config.yaml
docker-compose.yaml
main.go
model/workflow.go

The entrypoint.sh spawns a worker process in the background. We might
want to override the entrypoint and have the worker and server in
separate containers (mostly for sanitizing the logs).
I also updated the README.md to reflect recent changes in the api.
changelog: title
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

docker: Initialized docker files workflows

---

.gitlab-ci.yml
LICENSE
LIC_FILES_CHKSUM.sha256

This PR depends on https://github.com/mendersoftware/mendertesting/pull/36 being approved/merged.
An smoke run on how it will look can be found in [Pipeline 104890658](https://gitlab.com/Northern.tech/Mender/workflows/pipelines/104890658).
These templates cover the exact same functionality. The idea is for this
repo to only need to specify custom checks (for example acceptance tests).

Re-create the Pipeline based on the new mendertesting templates

---

store/mongo/datastore_mongo.go

Change the order of insertion of the Job in the queue and generic jobs
collections. If we insert the job in the queue before inserting it into
the generic jobs collection, we can have a race condition when a worker
picks up the job before the server completed the insertion.

Avoid race condition when starting a workflow

---

.gitlab-ci.yml
docker-compose.yml

Now that the template supports defining a custom Dockerfile, we can use
it to build/publish workflows-worker image in addition to the server
one.
The main motivation is to keep alignment with the rest, easing
maintenance when introducing changes in our publish policies (i.e.
if/when we want to publish feature/* based images).

Pipeline: use template to build/publish Docker images

---

.gitignore
Dockerfile.acceptance-testing.worker
Dockerfile.worker
tests/mmock/inventory_POST_devices_v2.json
tests/tests/test_update_device_status.py
worker/update_device_status.json

Update device status workflow
--
* **deviceauth** calls _update_device_status_ [[1](https://github.com/mendersoftware/workflows/pull/40)] workflow to propagate information on device status to inventory.
* **inventory** exposes internal API to set status for a list of devices [[2](https://github.com/mendersoftware/inventory-enterprise/pull/24)].
* _/filters/search_ can be use by UI to get list of devices as a single place of information.
related PRs:
* [1] https://github.com/mendersoftware/workflows/pull/40
* [2] https://github.com/mendersoftware/inventory/pull/162
* [3] https://github.com/mendersoftware/deviceauth/pull/324
ChangeLog:none

MEN-3240 update device status workflow

---

docs/workflows_api.yml

* [API spec] Consistently use host hosted.mender.io across all repos
* [API spec] Consistently use https schemes across all repos

API spec fixes: schema and hostname

---

app/worker/http.go
app/worker/http_test.go
app/worker/utils.go
go.mod
model/job.go
model/workflow.go
model/workflow_test.go
vendor/modules.txt

This commit brings in go template to specify http task's request body and adds an additional optionalParameters to the workflow structure (this attribute is merely for documentation purposes as it's not actually used).
Moreover, I also added support for yaml-file workflow definitions as I find it more readable, and changed the default http task failure criteria to include erroneous http status codes ( >= 400).

MEN-3619: Optional input parameters and go template request body

---

api/http/logger.go
api/http/router.go
go.mod
go.sum
vendor/modules.txt

The new logger uses logrus and exports key-values that are compatible
with the ones of the other Mender servicees.

MC-3311: replace gin-gonic logger with a custom logrus one

---

api/http/workflow.go
api/http/workflow_test.go
store/mongo/datastore_mongo.go

This PR makes some tiny adjustments to the `GET /health` endpoint aligning the implementation with the other services.
Most importantly: the return code from successful `GET /health` is changed to 204.

Align health check endpoints

---

.gitlab-ci.yml

This repo was missed in the initial round because it had a custom
publish:acceptance job.

QA-221: Acceptance tests: migrate to coveralls

---

tests/tests/test_update_device_status.py
worker/update_device_status.json

workflow now accepts devices instead of device ids;
each device object from devices contains id and revision;
revision field is needed for the new device status synchronization flow;

modify update_device_status workflow

---

Dockerfile
Dockerfile.acceptance-testing
Dockerfile.acceptance-testing.worker
Dockerfile.worker
go.sum

This reverts commit 32ca03dc873e17e853d0af5c0c2c44c826a469b9.
Fix inability to upload acceptance test coverage.
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

Revert "Changelog:All: Bump golang from 1.14-alpine3.12 to 1.15.4-alpine3.12"

---

worker/provision_device.json

The deviceonnect related changes to the workflow require the increment
of the version number of the workflow, otherwise the workflow server and
workers won't pick up the new version.

Bump the version of the provision_device workflow

---

.gitlab-ci.yml

Following upstream update. See
https://github.com/mendersoftware/mendertesting/pull/141
(cherry picked from commit a87a263c7385f64df1508267d3b2a88991c74d6e)

1.3.x: [pipeline] Switch from dependencies to needs

---

.gitlab-ci.yml

Following upstream update. See
https://github.com/mendersoftware/mendertesting/pull/141
(cherry picked from commit a87a263c7385f64df1508267d3b2a88991c74d6e)

1.1.x: [pipeline] Switch from dependencies to needs

---

api/http/logger.go

All the other Mender microservices are logging response time in seconds.

Log response time in seconds instead of milliseconds, to make it consistent

---

app/worker/process.go
store/mongo/datastore_mongo.go

When starting a workflow, we insert in the `jobs` collections first,
then in the `job_queue` one. For this reason, it doesn't make sense to
use upserts, as it will never happen the `jobs` collection won't contain
the job which is queued in the `job_queue` collection.
This commit should fix issues like:
```
Jul 20, 2021 @ 16:42:28.080 multiple write errors: [{write errors: [{E11000 duplicate key error collection: workflows.jobs index: _id_ dup key: { _id: \"60f6fcf4c3cceecd56968147\" }}]}, {<nil>}]
```

MEN-4923: do not use upsert when acquiring jobs

---

app/worker/smtp.go
app/worker/smtp_test.go

GMail doesn't display the HTML version of the message if it appears in
the first part of the mime/alternative. Move it to the last part to make
it display correctly. At the same time, improve the MIME headers setting
the charset to "UTF-8".

MEN-5083: HTML version in mime/alternative must be the last part

---

Dockerfile.acceptance-testing.worker
Dockerfile.worker
Makefile
tests/docker-compose.acceptance.yml
tests/mmock/azure-iot-manager_POST_devices.json
tests/mmock/azure-iot-manager_POST_devices_with_tenant_id.json
worker/decommission_device.json
worker/provision_device.json
worker/submit_device_configuration.json

New workflow submit_configuration calling the `PATCH /configuration` endpoint in mendersoftware/deviceconfig#85 as part of mendersoftware/azure-iot-manager#9.

[MEN-5153] Integrate azure-iot-manager with provision/decomission and submit configuration

---

Dockerfile
Dockerfile.acceptance-testing
Dockerfile.acceptance-testing.worker
Dockerfile.worker

this reverts #205, which reverted #201, this _should_ now be unproblematic, due to the changed setup of mendersoftware/create-artifact-worker#98

Revert Revert scratch

---

main.go

Allows backward compatibility in helm/k8s deployments.

chore: Bind migration skip-* flags to env variables

---

app/worker/timer.go
app/worker/worker.go
app/worker/worker_group.go

* Moved logic around worker go routines to worker_group.go
* Addressed concurrency issue where the worker enters a deadlock if the
"sidecar" Go routine is being blocked.
* Added missing call to unsubscribe before closing the jobChan which
could cause the application to panic (send on closed channel).
* Changed the logic of the main Go routine:
* The main routine waits for all workers to finish before cancelling
the context. The termination is initiated by closing the jobChan.
* The main routine starts terminating all workers as soon as the first
one quits.
* The sync.WaitGroup is replaced by a channel+counter equivalent to
allow select on multiple channels when waiting for termination (e.g.
another signal).
* Added context and TTL options to the sidecar routine to prevent blocking forever

MEN-7214: Fix concurrency issues with workflows-worker
